from setuptools import setup, find_packages

setup(
    name="ultralytics",
    version="0.0.1",  # Set this to the appropriate version
    description="Ultralytics YOLOv8 for SOTA object detection, multi-object tracking, instance segmentation, pose estimation and image classification.",
    author="Glenn Jocher, Ayush Chaurasia, Jing Qiu",
    license="AGPL-3.0",
    packages=find_packages(include=["ultralytics", "ultralytics.*"]),
    install_requires=[
        "matplotlib>=3.3.0",
        "opencv-python>=4.6.0",
        "pillow>=7.1.2",
        "pyyaml>=5.3.1",
        "requests>=2.23.0",
        "scipy>=1.4.1",
        "torch>=1.8.0",
        "torchvision>=0.9.0",
        "tqdm>=4.64.0",
        "psutil",
        "py-cpuinfo",
        "thop>=0.1.1",
        "pandas>=1.1.4",
        "seaborn>=0.11.0",
    ],
    extras_require={
        "dev": [
            "ipython",
            "check-manifest",
            "pre-commit",
            "pytest",
            "pytest-cov",
            "coverage[toml]",
            "mkdocs-material>=9.5.9",
            "mkdocstrings[python]",
            "mkdocs-jupyter",
            "mkdocs-redirects",
            "mkdocs-ultralytics-plugin>=0.0.44",
        ],
        "export": [
            "onnx>=1.12.0",
            "coremltools>=7.0; platform_system != 'Windows' and python_version <= '3.11'",
            "openvino>=2024.0.0",
            "tensorflow<=2.13.1; python_version <= '3.11'",
            "tensorflowjs>=3.9.0; python_version <= '3.11'",
        ],
        "explorer": [
            "lancedb",
            "duckdb<=0.9.2",
            "streamlit",
        ],
        "logging": [
            "comet",
            "tensorboard>=2.13.0",
            "dvclive>=2.12.0",
        ],
        "extra": [
            "hub-sdk>=0.0.5",
            "ipython",
            "albumentations>=1.0.3",
            "pycocotools>=2.0.7",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Education",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Software Development",
        "Topic :: Scientific/Engineering",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Image Recognition",
        "Operating System :: POSIX :: Linux",
        "Operating System :: MacOS",
        "Operating System :: Microsoft :: Windows",
    ],
)
